// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/Done-0/jank/pkg/serve/controller"
	impl2 "github.com/Done-0/jank/pkg/serve/mapper/impl"
	"github.com/Done-0/jank/pkg/serve/service/impl"
)

// Injectors from wire.go:

// NewPluginController 使用 Wire 初始化插件控制器
func NewPluginController() (*controller.PluginController, error) {
	pluginService := impl.NewPluginService()
	pluginController := controller.NewPluginController(pluginService)
	return pluginController, nil
}

// NewRBACController 使用 Wire 初始化RBAC控制器
func NewRBACController() (*controller.RBACController, error) {
	rbacMapper := impl2.NewRBACMapper()
	rbacService := impl.NewRBACService(rbacMapper)
	rbacController := controller.NewRBACController(rbacService)
	return rbacController, nil
}
